// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

// Protobuf Java Version: 3.25.6
package product.proto;

public interface GetProductRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.GetProductResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.product.Product product = 1;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.product.Product product = 1;</code>
   * @return The product.
   */
  product.proto.Product getProduct();
  /**
   * <code>.product.Product product = 1;</code>
   */
  product.proto.ProductOrBuilder getProductOrBuilder();
}
