// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

// Protobuf Java Version: 3.25.6
package product.proto;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string picture = 4;</code>
   * @return The picture.
   */
  java.lang.String getPicture();
  /**
   * <code>string picture = 4;</code>
   * @return The bytes for picture.
   */
  com.google.protobuf.ByteString
      getPictureBytes();

  /**
   * <code>float price = 5;</code>
   * @return The price.
   */
  float getPrice();

  /**
   * <code>repeated string categories = 6;</code>
   * @return A list containing the categories.
   */
  java.util.List<java.lang.String>
      getCategoriesList();
  /**
   * <code>repeated string categories = 6;</code>
   * @return The count of categories.
   */
  int getCategoriesCount();
  /**
   * <code>repeated string categories = 6;</code>
   * @param index The index of the element to return.
   * @return The categories at the given index.
   */
  java.lang.String getCategories(int index);
  /**
   * <code>repeated string categories = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the categories at the given index.
   */
  com.google.protobuf.ByteString
      getCategoriesBytes(int index);
}
