// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

// Protobuf Java Version: 3.25.6
package product.proto;

public interface SearchProductsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.SearchProductsReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
