// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

// Protobuf Java Version: 3.25.6
package product.proto;

public interface SearchProductsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.SearchProductsResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .product.Product results = 1;</code>
   */
  java.util.List<product.proto.Product> 
      getResultsList();
  /**
   * <code>repeated .product.Product results = 1;</code>
   */
  product.proto.Product getResults(int index);
  /**
   * <code>repeated .product.Product results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .product.Product results = 1;</code>
   */
  java.util.List<? extends product.proto.ProductOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .product.Product results = 1;</code>
   */
  product.proto.ProductOrBuilder getResultsOrBuilder(
      int index);
}
