// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

// Protobuf Java Version: 3.25.6
package checkout.proto;

public interface CheckoutReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkout.CheckoutReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string firstname = 2;</code>
   * @return The firstname.
   */
  java.lang.String getFirstname();
  /**
   * <code>string firstname = 2;</code>
   * @return The bytes for firstname.
   */
  com.google.protobuf.ByteString
      getFirstnameBytes();

  /**
   * <code>string lastname = 3;</code>
   * @return The lastname.
   */
  java.lang.String getLastname();
  /**
   * <code>string lastname = 3;</code>
   * @return The bytes for lastname.
   */
  com.google.protobuf.ByteString
      getLastnameBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>.checkout.Address address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.checkout.Address address = 5;</code>
   * @return The address.
   */
  checkout.proto.Address getAddress();
  /**
   * <code>.checkout.Address address = 5;</code>
   */
  checkout.proto.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>.payment.CreditCardInfo credit_card = 6;</code>
   * @return Whether the creditCard field is set.
   */
  boolean hasCreditCard();
  /**
   * <code>.payment.CreditCardInfo credit_card = 6;</code>
   * @return The creditCard.
   */
  payment.proto.CreditCardInfo getCreditCard();
  /**
   * <code>.payment.CreditCardInfo credit_card = 6;</code>
   */
  payment.proto.CreditCardInfoOrBuilder getCreditCardOrBuilder();
}
