// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

// Protobuf Java Version: 3.25.6
package checkout.proto;

/**
 * Protobuf type {@code checkout.CheckoutReq}
 */
public final class CheckoutReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:checkout.CheckoutReq)
    CheckoutReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckoutReq.newBuilder() to construct.
  private CheckoutReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckoutReq() {
    firstname_ = "";
    lastname_ = "";
    email_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CheckoutReq();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return checkout.proto.CheckoutProto.internal_static_checkout_CheckoutReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return checkout.proto.CheckoutProto.internal_static_checkout_CheckoutReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            checkout.proto.CheckoutReq.class, checkout.proto.CheckoutReq.Builder.class);
  }

  private int bitField0_;
  public static final int USER_ID_FIELD_NUMBER = 1;
  private int userId_ = 0;
  /**
   * <code>uint32 user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public int getUserId() {
    return userId_;
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object firstname_ = "";
  /**
   * <code>string firstname = 2;</code>
   * @return The firstname.
   */
  @java.lang.Override
  public java.lang.String getFirstname() {
    java.lang.Object ref = firstname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstname_ = s;
      return s;
    }
  }
  /**
   * <code>string firstname = 2;</code>
   * @return The bytes for firstname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstnameBytes() {
    java.lang.Object ref = firstname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastname_ = "";
  /**
   * <code>string lastname = 3;</code>
   * @return The lastname.
   */
  @java.lang.Override
  public java.lang.String getLastname() {
    java.lang.Object ref = lastname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastname_ = s;
      return s;
    }
  }
  /**
   * <code>string lastname = 3;</code>
   * @return The bytes for lastname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastnameBytes() {
    java.lang.Object ref = lastname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 5;
  private checkout.proto.Address address_;
  /**
   * <code>.checkout.Address address = 5;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.checkout.Address address = 5;</code>
   * @return The address.
   */
  @java.lang.Override
  public checkout.proto.Address getAddress() {
    return address_ == null ? checkout.proto.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.checkout.Address address = 5;</code>
   */
  @java.lang.Override
  public checkout.proto.AddressOrBuilder getAddressOrBuilder() {
    return address_ == null ? checkout.proto.Address.getDefaultInstance() : address_;
  }

  public static final int CREDIT_CARD_FIELD_NUMBER = 6;
  private payment.proto.CreditCardInfo creditCard_;
  /**
   * <code>.payment.CreditCardInfo credit_card = 6;</code>
   * @return Whether the creditCard field is set.
   */
  @java.lang.Override
  public boolean hasCreditCard() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.payment.CreditCardInfo credit_card = 6;</code>
   * @return The creditCard.
   */
  @java.lang.Override
  public payment.proto.CreditCardInfo getCreditCard() {
    return creditCard_ == null ? payment.proto.CreditCardInfo.getDefaultInstance() : creditCard_;
  }
  /**
   * <code>.payment.CreditCardInfo credit_card = 6;</code>
   */
  @java.lang.Override
  public payment.proto.CreditCardInfoOrBuilder getCreditCardOrBuilder() {
    return creditCard_ == null ? payment.proto.CreditCardInfo.getDefaultInstance() : creditCard_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0) {
      output.writeUInt32(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getAddress());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getCreditCard());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAddress());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCreditCard());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof checkout.proto.CheckoutReq)) {
      return super.equals(obj);
    }
    checkout.proto.CheckoutReq other = (checkout.proto.CheckoutReq) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (!getFirstname()
        .equals(other.getFirstname())) return false;
    if (!getLastname()
        .equals(other.getLastname())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (hasCreditCard() != other.hasCreditCard()) return false;
    if (hasCreditCard()) {
      if (!getCreditCard()
          .equals(other.getCreditCard())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstname().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastname().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (hasCreditCard()) {
      hash = (37 * hash) + CREDIT_CARD_FIELD_NUMBER;
      hash = (53 * hash) + getCreditCard().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static checkout.proto.CheckoutReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static checkout.proto.CheckoutReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static checkout.proto.CheckoutReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static checkout.proto.CheckoutReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static checkout.proto.CheckoutReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static checkout.proto.CheckoutReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static checkout.proto.CheckoutReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static checkout.proto.CheckoutReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static checkout.proto.CheckoutReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static checkout.proto.CheckoutReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static checkout.proto.CheckoutReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static checkout.proto.CheckoutReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(checkout.proto.CheckoutReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code checkout.CheckoutReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:checkout.CheckoutReq)
      checkout.proto.CheckoutReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return checkout.proto.CheckoutProto.internal_static_checkout_CheckoutReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return checkout.proto.CheckoutProto.internal_static_checkout_CheckoutReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              checkout.proto.CheckoutReq.class, checkout.proto.CheckoutReq.Builder.class);
    }

    // Construct using checkout.proto.CheckoutReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
        getCreditCardFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0;
      firstname_ = "";
      lastname_ = "";
      email_ = "";
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      creditCard_ = null;
      if (creditCardBuilder_ != null) {
        creditCardBuilder_.dispose();
        creditCardBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return checkout.proto.CheckoutProto.internal_static_checkout_CheckoutReq_descriptor;
    }

    @java.lang.Override
    public checkout.proto.CheckoutReq getDefaultInstanceForType() {
      return checkout.proto.CheckoutReq.getDefaultInstance();
    }

    @java.lang.Override
    public checkout.proto.CheckoutReq build() {
      checkout.proto.CheckoutReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public checkout.proto.CheckoutReq buildPartial() {
      checkout.proto.CheckoutReq result = new checkout.proto.CheckoutReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(checkout.proto.CheckoutReq result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.firstname_ = firstname_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lastname_ = lastname_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.email_ = email_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.address_ = addressBuilder_ == null
            ? address_
            : addressBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.creditCard_ = creditCardBuilder_ == null
            ? creditCard_
            : creditCardBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof checkout.proto.CheckoutReq) {
        return mergeFrom((checkout.proto.CheckoutReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(checkout.proto.CheckoutReq other) {
      if (other == checkout.proto.CheckoutReq.getDefaultInstance()) return this;
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (!other.getFirstname().isEmpty()) {
        firstname_ = other.firstname_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getLastname().isEmpty()) {
        lastname_ = other.lastname_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.hasCreditCard()) {
        mergeCreditCard(other.getCreditCard());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              firstname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              lastname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getAddressFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getCreditCardFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int userId_ ;
    /**
     * <code>uint32 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>uint32 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(int value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object firstname_ = "";
    /**
     * <code>string firstname = 2;</code>
     * @return The firstname.
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firstname = 2;</code>
     * @return The bytes for firstname.
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firstname = 2;</code>
     * @param value The firstname to set.
     * @return This builder for chaining.
     */
    public Builder setFirstname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      firstname_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string firstname = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstname() {
      firstname_ = getDefaultInstance().getFirstname();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string firstname = 2;</code>
     * @param value The bytes for firstname to set.
     * @return This builder for chaining.
     */
    public Builder setFirstnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      firstname_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object lastname_ = "";
    /**
     * <code>string lastname = 3;</code>
     * @return The lastname.
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastname = 3;</code>
     * @return The bytes for lastname.
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastname = 3;</code>
     * @param value The lastname to set.
     * @return This builder for chaining.
     */
    public Builder setLastname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastname_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string lastname = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastname() {
      lastname_ = getDefaultInstance().getLastname();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string lastname = 3;</code>
     * @param value The bytes for lastname to set.
     * @return This builder for chaining.
     */
    public Builder setLastnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastname_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private checkout.proto.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        checkout.proto.Address, checkout.proto.Address.Builder, checkout.proto.AddressOrBuilder> addressBuilder_;
    /**
     * <code>.checkout.Address address = 5;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.checkout.Address address = 5;</code>
     * @return The address.
     */
    public checkout.proto.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? checkout.proto.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.checkout.Address address = 5;</code>
     */
    public Builder setAddress(checkout.proto.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
      } else {
        addressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.checkout.Address address = 5;</code>
     */
    public Builder setAddress(
        checkout.proto.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.checkout.Address address = 5;</code>
     */
    public Builder mergeAddress(checkout.proto.Address value) {
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          address_ != null &&
          address_ != checkout.proto.Address.getDefaultInstance()) {
          getAddressBuilder().mergeFrom(value);
        } else {
          address_ = value;
        }
      } else {
        addressBuilder_.mergeFrom(value);
      }
      if (address_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.checkout.Address address = 5;</code>
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000010);
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.checkout.Address address = 5;</code>
     */
    public checkout.proto.Address.Builder getAddressBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.checkout.Address address = 5;</code>
     */
    public checkout.proto.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            checkout.proto.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.checkout.Address address = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        checkout.proto.Address, checkout.proto.Address.Builder, checkout.proto.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            checkout.proto.Address, checkout.proto.Address.Builder, checkout.proto.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private payment.proto.CreditCardInfo creditCard_;
    private com.google.protobuf.SingleFieldBuilderV3<
        payment.proto.CreditCardInfo, payment.proto.CreditCardInfo.Builder, payment.proto.CreditCardInfoOrBuilder> creditCardBuilder_;
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     * @return Whether the creditCard field is set.
     */
    public boolean hasCreditCard() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     * @return The creditCard.
     */
    public payment.proto.CreditCardInfo getCreditCard() {
      if (creditCardBuilder_ == null) {
        return creditCard_ == null ? payment.proto.CreditCardInfo.getDefaultInstance() : creditCard_;
      } else {
        return creditCardBuilder_.getMessage();
      }
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     */
    public Builder setCreditCard(payment.proto.CreditCardInfo value) {
      if (creditCardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        creditCard_ = value;
      } else {
        creditCardBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     */
    public Builder setCreditCard(
        payment.proto.CreditCardInfo.Builder builderForValue) {
      if (creditCardBuilder_ == null) {
        creditCard_ = builderForValue.build();
      } else {
        creditCardBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     */
    public Builder mergeCreditCard(payment.proto.CreditCardInfo value) {
      if (creditCardBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          creditCard_ != null &&
          creditCard_ != payment.proto.CreditCardInfo.getDefaultInstance()) {
          getCreditCardBuilder().mergeFrom(value);
        } else {
          creditCard_ = value;
        }
      } else {
        creditCardBuilder_.mergeFrom(value);
      }
      if (creditCard_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     */
    public Builder clearCreditCard() {
      bitField0_ = (bitField0_ & ~0x00000020);
      creditCard_ = null;
      if (creditCardBuilder_ != null) {
        creditCardBuilder_.dispose();
        creditCardBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     */
    public payment.proto.CreditCardInfo.Builder getCreditCardBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getCreditCardFieldBuilder().getBuilder();
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     */
    public payment.proto.CreditCardInfoOrBuilder getCreditCardOrBuilder() {
      if (creditCardBuilder_ != null) {
        return creditCardBuilder_.getMessageOrBuilder();
      } else {
        return creditCard_ == null ?
            payment.proto.CreditCardInfo.getDefaultInstance() : creditCard_;
      }
    }
    /**
     * <code>.payment.CreditCardInfo credit_card = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        payment.proto.CreditCardInfo, payment.proto.CreditCardInfo.Builder, payment.proto.CreditCardInfoOrBuilder> 
        getCreditCardFieldBuilder() {
      if (creditCardBuilder_ == null) {
        creditCardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            payment.proto.CreditCardInfo, payment.proto.CreditCardInfo.Builder, payment.proto.CreditCardInfoOrBuilder>(
                getCreditCard(),
                getParentForChildren(),
                isClean());
        creditCard_ = null;
      }
      return creditCardBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:checkout.CheckoutReq)
  }

  // @@protoc_insertion_point(class_scope:checkout.CheckoutReq)
  private static final checkout.proto.CheckoutReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new checkout.proto.CheckoutReq();
  }

  public static checkout.proto.CheckoutReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckoutReq>
      PARSER = new com.google.protobuf.AbstractParser<CheckoutReq>() {
    @java.lang.Override
    public CheckoutReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckoutReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckoutReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public checkout.proto.CheckoutReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

