// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

// Protobuf Java Version: 3.25.6
package checkout.proto;

public interface CheckoutRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkout.CheckoutResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>string transaction_id = 2;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 2;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();
}
