// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface AddItemRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.AddItemResp)
    com.google.protobuf.MessageOrBuilder {
}
