// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface CartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.Cart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>repeated .cart.CartItem items = 2;</code>
   */
  java.util.List<order.proto.CartItem> 
      getItemsList();
  /**
   * <code>repeated .cart.CartItem items = 2;</code>
   */
  order.proto.CartItem getItems(int index);
  /**
   * <code>repeated .cart.CartItem items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .cart.CartItem items = 2;</code>
   */
  java.util.List<? extends order.proto.CartItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .cart.CartItem items = 2;</code>
   */
  order.proto.CartItemOrBuilder getItemsOrBuilder(
      int index);
}
