// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface GetCartRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.GetCartResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cart.Cart cart = 1;</code>
   * @return Whether the cart field is set.
   */
  boolean hasCart();
  /**
   * <code>.cart.Cart cart = 1;</code>
   * @return The cart.
   */
  order.proto.Cart getCart();
  /**
   * <code>.cart.Cart cart = 1;</code>
   */
  order.proto.CartOrBuilder getCartOrBuilder();
}
