// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

// Protobuf Java Version: 3.25.6
package order.proto;

/**
 * Protobuf type {@code cart.GetCartResp}
 */
public final class GetCartResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cart.GetCartResp)
    GetCartRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCartResp.newBuilder() to construct.
  private GetCartResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCartResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetCartResp();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return order.proto.CartProto.internal_static_cart_GetCartResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return order.proto.CartProto.internal_static_cart_GetCartResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            order.proto.GetCartResp.class, order.proto.GetCartResp.Builder.class);
  }

  private int bitField0_;
  public static final int CART_FIELD_NUMBER = 1;
  private order.proto.Cart cart_;
  /**
   * <code>.cart.Cart cart = 1;</code>
   * @return Whether the cart field is set.
   */
  @java.lang.Override
  public boolean hasCart() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.cart.Cart cart = 1;</code>
   * @return The cart.
   */
  @java.lang.Override
  public order.proto.Cart getCart() {
    return cart_ == null ? order.proto.Cart.getDefaultInstance() : cart_;
  }
  /**
   * <code>.cart.Cart cart = 1;</code>
   */
  @java.lang.Override
  public order.proto.CartOrBuilder getCartOrBuilder() {
    return cart_ == null ? order.proto.Cart.getDefaultInstance() : cart_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCart());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCart());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof order.proto.GetCartResp)) {
      return super.equals(obj);
    }
    order.proto.GetCartResp other = (order.proto.GetCartResp) obj;

    if (hasCart() != other.hasCart()) return false;
    if (hasCart()) {
      if (!getCart()
          .equals(other.getCart())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCart()) {
      hash = (37 * hash) + CART_FIELD_NUMBER;
      hash = (53 * hash) + getCart().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static order.proto.GetCartResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static order.proto.GetCartResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static order.proto.GetCartResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static order.proto.GetCartResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static order.proto.GetCartResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static order.proto.GetCartResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static order.proto.GetCartResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static order.proto.GetCartResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static order.proto.GetCartResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static order.proto.GetCartResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static order.proto.GetCartResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static order.proto.GetCartResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(order.proto.GetCartResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cart.GetCartResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cart.GetCartResp)
      order.proto.GetCartRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return order.proto.CartProto.internal_static_cart_GetCartResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return order.proto.CartProto.internal_static_cart_GetCartResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              order.proto.GetCartResp.class, order.proto.GetCartResp.Builder.class);
    }

    // Construct using order.proto.GetCartResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCartFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cart_ = null;
      if (cartBuilder_ != null) {
        cartBuilder_.dispose();
        cartBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return order.proto.CartProto.internal_static_cart_GetCartResp_descriptor;
    }

    @java.lang.Override
    public order.proto.GetCartResp getDefaultInstanceForType() {
      return order.proto.GetCartResp.getDefaultInstance();
    }

    @java.lang.Override
    public order.proto.GetCartResp build() {
      order.proto.GetCartResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public order.proto.GetCartResp buildPartial() {
      order.proto.GetCartResp result = new order.proto.GetCartResp(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(order.proto.GetCartResp result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cart_ = cartBuilder_ == null
            ? cart_
            : cartBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof order.proto.GetCartResp) {
        return mergeFrom((order.proto.GetCartResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(order.proto.GetCartResp other) {
      if (other == order.proto.GetCartResp.getDefaultInstance()) return this;
      if (other.hasCart()) {
        mergeCart(other.getCart());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCartFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private order.proto.Cart cart_;
    private com.google.protobuf.SingleFieldBuilderV3<
        order.proto.Cart, order.proto.Cart.Builder, order.proto.CartOrBuilder> cartBuilder_;
    /**
     * <code>.cart.Cart cart = 1;</code>
     * @return Whether the cart field is set.
     */
    public boolean hasCart() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.cart.Cart cart = 1;</code>
     * @return The cart.
     */
    public order.proto.Cart getCart() {
      if (cartBuilder_ == null) {
        return cart_ == null ? order.proto.Cart.getDefaultInstance() : cart_;
      } else {
        return cartBuilder_.getMessage();
      }
    }
    /**
     * <code>.cart.Cart cart = 1;</code>
     */
    public Builder setCart(order.proto.Cart value) {
      if (cartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cart_ = value;
      } else {
        cartBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cart.Cart cart = 1;</code>
     */
    public Builder setCart(
        order.proto.Cart.Builder builderForValue) {
      if (cartBuilder_ == null) {
        cart_ = builderForValue.build();
      } else {
        cartBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cart.Cart cart = 1;</code>
     */
    public Builder mergeCart(order.proto.Cart value) {
      if (cartBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          cart_ != null &&
          cart_ != order.proto.Cart.getDefaultInstance()) {
          getCartBuilder().mergeFrom(value);
        } else {
          cart_ = value;
        }
      } else {
        cartBuilder_.mergeFrom(value);
      }
      if (cart_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.cart.Cart cart = 1;</code>
     */
    public Builder clearCart() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cart_ = null;
      if (cartBuilder_ != null) {
        cartBuilder_.dispose();
        cartBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.cart.Cart cart = 1;</code>
     */
    public order.proto.Cart.Builder getCartBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCartFieldBuilder().getBuilder();
    }
    /**
     * <code>.cart.Cart cart = 1;</code>
     */
    public order.proto.CartOrBuilder getCartOrBuilder() {
      if (cartBuilder_ != null) {
        return cartBuilder_.getMessageOrBuilder();
      } else {
        return cart_ == null ?
            order.proto.Cart.getDefaultInstance() : cart_;
      }
    }
    /**
     * <code>.cart.Cart cart = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        order.proto.Cart, order.proto.Cart.Builder, order.proto.CartOrBuilder> 
        getCartFieldBuilder() {
      if (cartBuilder_ == null) {
        cartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            order.proto.Cart, order.proto.Cart.Builder, order.proto.CartOrBuilder>(
                getCart(),
                getParentForChildren(),
                isClean());
        cart_ = null;
      }
      return cartBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cart.GetCartResp)
  }

  // @@protoc_insertion_point(class_scope:cart.GetCartResp)
  private static final order.proto.GetCartResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new order.proto.GetCartResp();
  }

  public static order.proto.GetCartResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCartResp>
      PARSER = new com.google.protobuf.AbstractParser<GetCartResp>() {
    @java.lang.Override
    public GetCartResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetCartResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCartResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public order.proto.GetCartResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

