// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface ListOrderReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.ListOrderReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
