// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface MarkOrderPaidRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.MarkOrderPaidResp)
    com.google.protobuf.MessageOrBuilder {
}
