// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.6
package order.proto;

/**
 * Protobuf type {@code order.PlaceOrderReq}
 */
public final class PlaceOrderReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:order.PlaceOrderReq)
    PlaceOrderReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlaceOrderReq.newBuilder() to construct.
  private PlaceOrderReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlaceOrderReq() {
    userCurrency_ = "";
    email_ = "";
    orderItems_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlaceOrderReq();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return order.proto.OrderProto.internal_static_order_PlaceOrderReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return order.proto.OrderProto.internal_static_order_PlaceOrderReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            order.proto.PlaceOrderReq.class, order.proto.PlaceOrderReq.Builder.class);
  }

  private int bitField0_;
  public static final int USER_ID_FIELD_NUMBER = 1;
  private int userId_ = 0;
  /**
   * <code>uint32 user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public int getUserId() {
    return userId_;
  }

  public static final int USER_CURRENCY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userCurrency_ = "";
  /**
   * <code>string user_currency = 2;</code>
   * @return The userCurrency.
   */
  @java.lang.Override
  public java.lang.String getUserCurrency() {
    java.lang.Object ref = userCurrency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userCurrency_ = s;
      return s;
    }
  }
  /**
   * <code>string user_currency = 2;</code>
   * @return The bytes for userCurrency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserCurrencyBytes() {
    java.lang.Object ref = userCurrency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private order.proto.Address address_;
  /**
   * <code>.order.Address address = 3;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.order.Address address = 3;</code>
   * @return The address.
   */
  @java.lang.Override
  public order.proto.Address getAddress() {
    return address_ == null ? order.proto.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.order.Address address = 3;</code>
   */
  @java.lang.Override
  public order.proto.AddressOrBuilder getAddressOrBuilder() {
    return address_ == null ? order.proto.Address.getDefaultInstance() : address_;
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_ITEMS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<order.proto.OrderItem> orderItems_;
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  @java.lang.Override
  public java.util.List<order.proto.OrderItem> getOrderItemsList() {
    return orderItems_;
  }
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends order.proto.OrderItemOrBuilder> 
      getOrderItemsOrBuilderList() {
    return orderItems_;
  }
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  @java.lang.Override
  public int getOrderItemsCount() {
    return orderItems_.size();
  }
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  @java.lang.Override
  public order.proto.OrderItem getOrderItems(int index) {
    return orderItems_.get(index);
  }
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  @java.lang.Override
  public order.proto.OrderItemOrBuilder getOrderItemsOrBuilder(
      int index) {
    return orderItems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0) {
      output.writeUInt32(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userCurrency_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userCurrency_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getAddress());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
    }
    for (int i = 0; i < orderItems_.size(); i++) {
      output.writeMessage(5, orderItems_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userCurrency_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userCurrency_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAddress());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
    }
    for (int i = 0; i < orderItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, orderItems_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof order.proto.PlaceOrderReq)) {
      return super.equals(obj);
    }
    order.proto.PlaceOrderReq other = (order.proto.PlaceOrderReq) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (!getUserCurrency()
        .equals(other.getUserCurrency())) return false;
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getOrderItemsList()
        .equals(other.getOrderItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (37 * hash) + USER_CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getUserCurrency().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (getOrderItemsCount() > 0) {
      hash = (37 * hash) + ORDER_ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static order.proto.PlaceOrderReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static order.proto.PlaceOrderReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static order.proto.PlaceOrderReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static order.proto.PlaceOrderReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static order.proto.PlaceOrderReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static order.proto.PlaceOrderReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static order.proto.PlaceOrderReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static order.proto.PlaceOrderReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static order.proto.PlaceOrderReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static order.proto.PlaceOrderReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static order.proto.PlaceOrderReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static order.proto.PlaceOrderReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(order.proto.PlaceOrderReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code order.PlaceOrderReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:order.PlaceOrderReq)
      order.proto.PlaceOrderReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return order.proto.OrderProto.internal_static_order_PlaceOrderReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return order.proto.OrderProto.internal_static_order_PlaceOrderReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              order.proto.PlaceOrderReq.class, order.proto.PlaceOrderReq.Builder.class);
    }

    // Construct using order.proto.PlaceOrderReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
        getOrderItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0;
      userCurrency_ = "";
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      email_ = "";
      if (orderItemsBuilder_ == null) {
        orderItems_ = java.util.Collections.emptyList();
      } else {
        orderItems_ = null;
        orderItemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return order.proto.OrderProto.internal_static_order_PlaceOrderReq_descriptor;
    }

    @java.lang.Override
    public order.proto.PlaceOrderReq getDefaultInstanceForType() {
      return order.proto.PlaceOrderReq.getDefaultInstance();
    }

    @java.lang.Override
    public order.proto.PlaceOrderReq build() {
      order.proto.PlaceOrderReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public order.proto.PlaceOrderReq buildPartial() {
      order.proto.PlaceOrderReq result = new order.proto.PlaceOrderReq(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(order.proto.PlaceOrderReq result) {
      if (orderItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          orderItems_ = java.util.Collections.unmodifiableList(orderItems_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.orderItems_ = orderItems_;
      } else {
        result.orderItems_ = orderItemsBuilder_.build();
      }
    }

    private void buildPartial0(order.proto.PlaceOrderReq result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userCurrency_ = userCurrency_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.address_ = addressBuilder_ == null
            ? address_
            : addressBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.email_ = email_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof order.proto.PlaceOrderReq) {
        return mergeFrom((order.proto.PlaceOrderReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(order.proto.PlaceOrderReq other) {
      if (other == order.proto.PlaceOrderReq.getDefaultInstance()) return this;
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (!other.getUserCurrency().isEmpty()) {
        userCurrency_ = other.userCurrency_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (orderItemsBuilder_ == null) {
        if (!other.orderItems_.isEmpty()) {
          if (orderItems_.isEmpty()) {
            orderItems_ = other.orderItems_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureOrderItemsIsMutable();
            orderItems_.addAll(other.orderItems_);
          }
          onChanged();
        }
      } else {
        if (!other.orderItems_.isEmpty()) {
          if (orderItemsBuilder_.isEmpty()) {
            orderItemsBuilder_.dispose();
            orderItemsBuilder_ = null;
            orderItems_ = other.orderItems_;
            bitField0_ = (bitField0_ & ~0x00000010);
            orderItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderItemsFieldBuilder() : null;
          } else {
            orderItemsBuilder_.addAllMessages(other.orderItems_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              userCurrency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getAddressFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              order.proto.OrderItem m =
                  input.readMessage(
                      order.proto.OrderItem.parser(),
                      extensionRegistry);
              if (orderItemsBuilder_ == null) {
                ensureOrderItemsIsMutable();
                orderItems_.add(m);
              } else {
                orderItemsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int userId_ ;
    /**
     * <code>uint32 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>uint32 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(int value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object userCurrency_ = "";
    /**
     * <code>string user_currency = 2;</code>
     * @return The userCurrency.
     */
    public java.lang.String getUserCurrency() {
      java.lang.Object ref = userCurrency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userCurrency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_currency = 2;</code>
     * @return The bytes for userCurrency.
     */
    public com.google.protobuf.ByteString
        getUserCurrencyBytes() {
      java.lang.Object ref = userCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_currency = 2;</code>
     * @param value The userCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setUserCurrency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userCurrency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string user_currency = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserCurrency() {
      userCurrency_ = getDefaultInstance().getUserCurrency();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string user_currency = 2;</code>
     * @param value The bytes for userCurrency to set.
     * @return This builder for chaining.
     */
    public Builder setUserCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userCurrency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private order.proto.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        order.proto.Address, order.proto.Address.Builder, order.proto.AddressOrBuilder> addressBuilder_;
    /**
     * <code>.order.Address address = 3;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.order.Address address = 3;</code>
     * @return The address.
     */
    public order.proto.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? order.proto.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.order.Address address = 3;</code>
     */
    public Builder setAddress(order.proto.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
      } else {
        addressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.order.Address address = 3;</code>
     */
    public Builder setAddress(
        order.proto.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.order.Address address = 3;</code>
     */
    public Builder mergeAddress(order.proto.Address value) {
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          address_ != null &&
          address_ != order.proto.Address.getDefaultInstance()) {
          getAddressBuilder().mergeFrom(value);
        } else {
          address_ = value;
        }
      } else {
        addressBuilder_.mergeFrom(value);
      }
      if (address_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.order.Address address = 3;</code>
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000004);
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.order.Address address = 3;</code>
     */
    public order.proto.Address.Builder getAddressBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.order.Address address = 3;</code>
     */
    public order.proto.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            order.proto.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.order.Address address = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        order.proto.Address, order.proto.Address.Builder, order.proto.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            order.proto.Address, order.proto.Address.Builder, order.proto.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.util.List<order.proto.OrderItem> orderItems_ =
      java.util.Collections.emptyList();
    private void ensureOrderItemsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        orderItems_ = new java.util.ArrayList<order.proto.OrderItem>(orderItems_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        order.proto.OrderItem, order.proto.OrderItem.Builder, order.proto.OrderItemOrBuilder> orderItemsBuilder_;

    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public java.util.List<order.proto.OrderItem> getOrderItemsList() {
      if (orderItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderItems_);
      } else {
        return orderItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public int getOrderItemsCount() {
      if (orderItemsBuilder_ == null) {
        return orderItems_.size();
      } else {
        return orderItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public order.proto.OrderItem getOrderItems(int index) {
      if (orderItemsBuilder_ == null) {
        return orderItems_.get(index);
      } else {
        return orderItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder setOrderItems(
        int index, order.proto.OrderItem value) {
      if (orderItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderItemsIsMutable();
        orderItems_.set(index, value);
        onChanged();
      } else {
        orderItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder setOrderItems(
        int index, order.proto.OrderItem.Builder builderForValue) {
      if (orderItemsBuilder_ == null) {
        ensureOrderItemsIsMutable();
        orderItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder addOrderItems(order.proto.OrderItem value) {
      if (orderItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderItemsIsMutable();
        orderItems_.add(value);
        onChanged();
      } else {
        orderItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder addOrderItems(
        int index, order.proto.OrderItem value) {
      if (orderItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderItemsIsMutable();
        orderItems_.add(index, value);
        onChanged();
      } else {
        orderItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder addOrderItems(
        order.proto.OrderItem.Builder builderForValue) {
      if (orderItemsBuilder_ == null) {
        ensureOrderItemsIsMutable();
        orderItems_.add(builderForValue.build());
        onChanged();
      } else {
        orderItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder addOrderItems(
        int index, order.proto.OrderItem.Builder builderForValue) {
      if (orderItemsBuilder_ == null) {
        ensureOrderItemsIsMutable();
        orderItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder addAllOrderItems(
        java.lang.Iterable<? extends order.proto.OrderItem> values) {
      if (orderItemsBuilder_ == null) {
        ensureOrderItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderItems_);
        onChanged();
      } else {
        orderItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder clearOrderItems() {
      if (orderItemsBuilder_ == null) {
        orderItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        orderItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public Builder removeOrderItems(int index) {
      if (orderItemsBuilder_ == null) {
        ensureOrderItemsIsMutable();
        orderItems_.remove(index);
        onChanged();
      } else {
        orderItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public order.proto.OrderItem.Builder getOrderItemsBuilder(
        int index) {
      return getOrderItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public order.proto.OrderItemOrBuilder getOrderItemsOrBuilder(
        int index) {
      if (orderItemsBuilder_ == null) {
        return orderItems_.get(index);  } else {
        return orderItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public java.util.List<? extends order.proto.OrderItemOrBuilder> 
         getOrderItemsOrBuilderList() {
      if (orderItemsBuilder_ != null) {
        return orderItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderItems_);
      }
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public order.proto.OrderItem.Builder addOrderItemsBuilder() {
      return getOrderItemsFieldBuilder().addBuilder(
          order.proto.OrderItem.getDefaultInstance());
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public order.proto.OrderItem.Builder addOrderItemsBuilder(
        int index) {
      return getOrderItemsFieldBuilder().addBuilder(
          index, order.proto.OrderItem.getDefaultInstance());
    }
    /**
     * <code>repeated .order.OrderItem order_items = 5;</code>
     */
    public java.util.List<order.proto.OrderItem.Builder> 
         getOrderItemsBuilderList() {
      return getOrderItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        order.proto.OrderItem, order.proto.OrderItem.Builder, order.proto.OrderItemOrBuilder> 
        getOrderItemsFieldBuilder() {
      if (orderItemsBuilder_ == null) {
        orderItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            order.proto.OrderItem, order.proto.OrderItem.Builder, order.proto.OrderItemOrBuilder>(
                orderItems_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        orderItems_ = null;
      }
      return orderItemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:order.PlaceOrderReq)
  }

  // @@protoc_insertion_point(class_scope:order.PlaceOrderReq)
  private static final order.proto.PlaceOrderReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new order.proto.PlaceOrderReq();
  }

  public static order.proto.PlaceOrderReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlaceOrderReq>
      PARSER = new com.google.protobuf.AbstractParser<PlaceOrderReq>() {
    @java.lang.Override
    public PlaceOrderReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlaceOrderReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlaceOrderReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public order.proto.PlaceOrderReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

