// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface PlaceOrderReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.PlaceOrderReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string user_currency = 2;</code>
   * @return The userCurrency.
   */
  java.lang.String getUserCurrency();
  /**
   * <code>string user_currency = 2;</code>
   * @return The bytes for userCurrency.
   */
  com.google.protobuf.ByteString
      getUserCurrencyBytes();

  /**
   * <code>.order.Address address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.order.Address address = 3;</code>
   * @return The address.
   */
  order.proto.Address getAddress();
  /**
   * <code>.order.Address address = 3;</code>
   */
  order.proto.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  java.util.List<order.proto.OrderItem> 
      getOrderItemsList();
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  order.proto.OrderItem getOrderItems(int index);
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  int getOrderItemsCount();
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  java.util.List<? extends order.proto.OrderItemOrBuilder> 
      getOrderItemsOrBuilderList();
  /**
   * <code>repeated .order.OrderItem order_items = 5;</code>
   */
  order.proto.OrderItemOrBuilder getOrderItemsOrBuilder(
      int index);
}
