// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface PlaceOrderRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.PlaceOrderResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.order.OrderResult order = 1;</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <code>.order.OrderResult order = 1;</code>
   * @return The order.
   */
  order.proto.OrderResult getOrder();
  /**
   * <code>.order.OrderResult order = 1;</code>
   */
  order.proto.OrderResultOrBuilder getOrderOrBuilder();
}
