// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

// Protobuf Java Version: 3.25.6
package payment.proto;

/**
 * Protobuf type {@code payment.CreditCardInfo}
 */
public final class CreditCardInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:payment.CreditCardInfo)
    CreditCardInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreditCardInfo.newBuilder() to construct.
  private CreditCardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreditCardInfo() {
    creditCardNumber_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreditCardInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return payment.proto.PaymentProto.internal_static_payment_CreditCardInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return payment.proto.PaymentProto.internal_static_payment_CreditCardInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            payment.proto.CreditCardInfo.class, payment.proto.CreditCardInfo.Builder.class);
  }

  public static final int CREDIT_CARD_NUMBER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object creditCardNumber_ = "";
  /**
   * <code>string credit_card_number = 1;</code>
   * @return The creditCardNumber.
   */
  @java.lang.Override
  public java.lang.String getCreditCardNumber() {
    java.lang.Object ref = creditCardNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creditCardNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string credit_card_number = 1;</code>
   * @return The bytes for creditCardNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreditCardNumberBytes() {
    java.lang.Object ref = creditCardNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creditCardNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREDIT_CARD_CVV_FIELD_NUMBER = 2;
  private int creditCardCvv_ = 0;
  /**
   * <code>int32 credit_card_cvv = 2;</code>
   * @return The creditCardCvv.
   */
  @java.lang.Override
  public int getCreditCardCvv() {
    return creditCardCvv_;
  }

  public static final int CREDIT_CARD_EXPIRATION_YEAR_FIELD_NUMBER = 3;
  private int creditCardExpirationYear_ = 0;
  /**
   * <code>int32 credit_card_expiration_year = 3;</code>
   * @return The creditCardExpirationYear.
   */
  @java.lang.Override
  public int getCreditCardExpirationYear() {
    return creditCardExpirationYear_;
  }

  public static final int CREDIT_CARD_EXPIRATION_MONTH_FIELD_NUMBER = 4;
  private int creditCardExpirationMonth_ = 0;
  /**
   * <code>int32 credit_card_expiration_month = 4;</code>
   * @return The creditCardExpirationMonth.
   */
  @java.lang.Override
  public int getCreditCardExpirationMonth() {
    return creditCardExpirationMonth_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creditCardNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, creditCardNumber_);
    }
    if (creditCardCvv_ != 0) {
      output.writeInt32(2, creditCardCvv_);
    }
    if (creditCardExpirationYear_ != 0) {
      output.writeInt32(3, creditCardExpirationYear_);
    }
    if (creditCardExpirationMonth_ != 0) {
      output.writeInt32(4, creditCardExpirationMonth_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creditCardNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, creditCardNumber_);
    }
    if (creditCardCvv_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, creditCardCvv_);
    }
    if (creditCardExpirationYear_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, creditCardExpirationYear_);
    }
    if (creditCardExpirationMonth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, creditCardExpirationMonth_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof payment.proto.CreditCardInfo)) {
      return super.equals(obj);
    }
    payment.proto.CreditCardInfo other = (payment.proto.CreditCardInfo) obj;

    if (!getCreditCardNumber()
        .equals(other.getCreditCardNumber())) return false;
    if (getCreditCardCvv()
        != other.getCreditCardCvv()) return false;
    if (getCreditCardExpirationYear()
        != other.getCreditCardExpirationYear()) return false;
    if (getCreditCardExpirationMonth()
        != other.getCreditCardExpirationMonth()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CREDIT_CARD_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCreditCardNumber().hashCode();
    hash = (37 * hash) + CREDIT_CARD_CVV_FIELD_NUMBER;
    hash = (53 * hash) + getCreditCardCvv();
    hash = (37 * hash) + CREDIT_CARD_EXPIRATION_YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getCreditCardExpirationYear();
    hash = (37 * hash) + CREDIT_CARD_EXPIRATION_MONTH_FIELD_NUMBER;
    hash = (53 * hash) + getCreditCardExpirationMonth();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static payment.proto.CreditCardInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static payment.proto.CreditCardInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static payment.proto.CreditCardInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static payment.proto.CreditCardInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static payment.proto.CreditCardInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static payment.proto.CreditCardInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static payment.proto.CreditCardInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static payment.proto.CreditCardInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static payment.proto.CreditCardInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static payment.proto.CreditCardInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static payment.proto.CreditCardInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static payment.proto.CreditCardInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(payment.proto.CreditCardInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code payment.CreditCardInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:payment.CreditCardInfo)
      payment.proto.CreditCardInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return payment.proto.PaymentProto.internal_static_payment_CreditCardInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return payment.proto.PaymentProto.internal_static_payment_CreditCardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              payment.proto.CreditCardInfo.class, payment.proto.CreditCardInfo.Builder.class);
    }

    // Construct using payment.proto.CreditCardInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      creditCardNumber_ = "";
      creditCardCvv_ = 0;
      creditCardExpirationYear_ = 0;
      creditCardExpirationMonth_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return payment.proto.PaymentProto.internal_static_payment_CreditCardInfo_descriptor;
    }

    @java.lang.Override
    public payment.proto.CreditCardInfo getDefaultInstanceForType() {
      return payment.proto.CreditCardInfo.getDefaultInstance();
    }

    @java.lang.Override
    public payment.proto.CreditCardInfo build() {
      payment.proto.CreditCardInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public payment.proto.CreditCardInfo buildPartial() {
      payment.proto.CreditCardInfo result = new payment.proto.CreditCardInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(payment.proto.CreditCardInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.creditCardNumber_ = creditCardNumber_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.creditCardCvv_ = creditCardCvv_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.creditCardExpirationYear_ = creditCardExpirationYear_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.creditCardExpirationMonth_ = creditCardExpirationMonth_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof payment.proto.CreditCardInfo) {
        return mergeFrom((payment.proto.CreditCardInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(payment.proto.CreditCardInfo other) {
      if (other == payment.proto.CreditCardInfo.getDefaultInstance()) return this;
      if (!other.getCreditCardNumber().isEmpty()) {
        creditCardNumber_ = other.creditCardNumber_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getCreditCardCvv() != 0) {
        setCreditCardCvv(other.getCreditCardCvv());
      }
      if (other.getCreditCardExpirationYear() != 0) {
        setCreditCardExpirationYear(other.getCreditCardExpirationYear());
      }
      if (other.getCreditCardExpirationMonth() != 0) {
        setCreditCardExpirationMonth(other.getCreditCardExpirationMonth());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              creditCardNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              creditCardCvv_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              creditCardExpirationYear_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              creditCardExpirationMonth_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object creditCardNumber_ = "";
    /**
     * <code>string credit_card_number = 1;</code>
     * @return The creditCardNumber.
     */
    public java.lang.String getCreditCardNumber() {
      java.lang.Object ref = creditCardNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creditCardNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string credit_card_number = 1;</code>
     * @return The bytes for creditCardNumber.
     */
    public com.google.protobuf.ByteString
        getCreditCardNumberBytes() {
      java.lang.Object ref = creditCardNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creditCardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string credit_card_number = 1;</code>
     * @param value The creditCardNumber to set.
     * @return This builder for chaining.
     */
    public Builder setCreditCardNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      creditCardNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string credit_card_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreditCardNumber() {
      creditCardNumber_ = getDefaultInstance().getCreditCardNumber();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string credit_card_number = 1;</code>
     * @param value The bytes for creditCardNumber to set.
     * @return This builder for chaining.
     */
    public Builder setCreditCardNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      creditCardNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int creditCardCvv_ ;
    /**
     * <code>int32 credit_card_cvv = 2;</code>
     * @return The creditCardCvv.
     */
    @java.lang.Override
    public int getCreditCardCvv() {
      return creditCardCvv_;
    }
    /**
     * <code>int32 credit_card_cvv = 2;</code>
     * @param value The creditCardCvv to set.
     * @return This builder for chaining.
     */
    public Builder setCreditCardCvv(int value) {

      creditCardCvv_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 credit_card_cvv = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreditCardCvv() {
      bitField0_ = (bitField0_ & ~0x00000002);
      creditCardCvv_ = 0;
      onChanged();
      return this;
    }

    private int creditCardExpirationYear_ ;
    /**
     * <code>int32 credit_card_expiration_year = 3;</code>
     * @return The creditCardExpirationYear.
     */
    @java.lang.Override
    public int getCreditCardExpirationYear() {
      return creditCardExpirationYear_;
    }
    /**
     * <code>int32 credit_card_expiration_year = 3;</code>
     * @param value The creditCardExpirationYear to set.
     * @return This builder for chaining.
     */
    public Builder setCreditCardExpirationYear(int value) {

      creditCardExpirationYear_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 credit_card_expiration_year = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreditCardExpirationYear() {
      bitField0_ = (bitField0_ & ~0x00000004);
      creditCardExpirationYear_ = 0;
      onChanged();
      return this;
    }

    private int creditCardExpirationMonth_ ;
    /**
     * <code>int32 credit_card_expiration_month = 4;</code>
     * @return The creditCardExpirationMonth.
     */
    @java.lang.Override
    public int getCreditCardExpirationMonth() {
      return creditCardExpirationMonth_;
    }
    /**
     * <code>int32 credit_card_expiration_month = 4;</code>
     * @param value The creditCardExpirationMonth to set.
     * @return This builder for chaining.
     */
    public Builder setCreditCardExpirationMonth(int value) {

      creditCardExpirationMonth_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 credit_card_expiration_month = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreditCardExpirationMonth() {
      bitField0_ = (bitField0_ & ~0x00000008);
      creditCardExpirationMonth_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:payment.CreditCardInfo)
  }

  // @@protoc_insertion_point(class_scope:payment.CreditCardInfo)
  private static final payment.proto.CreditCardInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new payment.proto.CreditCardInfo();
  }

  public static payment.proto.CreditCardInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreditCardInfo>
      PARSER = new com.google.protobuf.AbstractParser<CreditCardInfo>() {
    @java.lang.Override
    public CreditCardInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreditCardInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreditCardInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public payment.proto.CreditCardInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

