// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

// Protobuf Java Version: 3.25.6
package payment.proto;

public interface ChargeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payment.ChargeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float amount = 1;</code>
   * @return The amount.
   */
  float getAmount();

  /**
   * <code>.payment.CreditCardInfo credit_card = 2;</code>
   * @return Whether the creditCard field is set.
   */
  boolean hasCreditCard();
  /**
   * <code>.payment.CreditCardInfo credit_card = 2;</code>
   * @return The creditCard.
   */
  payment.proto.CreditCardInfo getCreditCard();
  /**
   * <code>.payment.CreditCardInfo credit_card = 2;</code>
   */
  payment.proto.CreditCardInfoOrBuilder getCreditCardOrBuilder();

  /**
   * <code>string order_id = 3;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 3;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>uint32 user_id = 4;</code>
   * @return The userId.
   */
  int getUserId();
}
