// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.6
package user.proto;

public interface RegisterRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.RegisterResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
