// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.6
package user.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_RegisterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_RegisterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_RegisterResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_RegisterResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_LoginReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_LoginReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_LoginResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_LoginResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\"H\n\013RegisterReq\022\r\n\005ema" +
      "il\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\030\n\020confirm_pa" +
      "ssword\030\003 \001(\t\"\037\n\014RegisterResp\022\017\n\007user_id\030" +
      "\001 \001(\005\"+\n\010LoginReq\022\r\n\005email\030\001 \001(\t\022\020\n\010pass" +
      "word\030\002 \001(\t\"\034\n\tLoginResp\022\017\n\007user_id\030\001 \001(\005" +
      "2n\n\013UserService\0223\n\010Register\022\021.user.Regis" +
      "terReq\032\022.user.RegisterResp\"\000\022*\n\005Login\022\016." +
      "user.LoginReq\032\017.user.LoginResp\"\000B\031\n\nuser" +
      ".protoB\tUserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_RegisterReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_RegisterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_RegisterReq_descriptor,
        new java.lang.String[] { "Email", "Password", "ConfirmPassword", });
    internal_static_user_RegisterResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_RegisterResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_RegisterResp_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_user_LoginReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_LoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_LoginReq_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_user_LoginResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_LoginResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_LoginResp_descriptor,
        new java.lang.String[] { "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
