// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface AddItemReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.AddItemReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>.cart.CartItem item = 2;</code>
   * @return Whether the item field is set.
   */
  boolean hasItem();
  /**
   * <code>.cart.CartItem item = 2;</code>
   * @return The item.
   */
  order.proto.CartItem getItem();
  /**
   * <code>.cart.CartItem item = 2;</code>
   */
  order.proto.CartItemOrBuilder getItemOrBuilder();
}
