// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public interface CartItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.CartItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 product_id = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
