// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

// Protobuf Java Version: 3.25.6
package order.proto;

public final class CartProto {
  private CartProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_CartItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_CartItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_AddItemReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_AddItemReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_AddItemResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_AddItemResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_EmptyCartReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_EmptyCartReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_GetCartReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_GetCartReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_GetCartResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_GetCartResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_Cart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_Cart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_EmptyCartResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_EmptyCartResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncart.proto\022\004cart\"0\n\010CartItem\022\022\n\nproduc" +
      "t_id\030\001 \001(\r\022\020\n\010quantity\030\002 \001(\005\";\n\nAddItemR" +
      "eq\022\017\n\007user_id\030\001 \001(\r\022\034\n\004item\030\002 \001(\0132\016.cart" +
      ".CartItem\"\r\n\013AddItemResp\"\037\n\014EmptyCartReq" +
      "\022\017\n\007user_id\030\001 \001(\r\"\035\n\nGetCartReq\022\017\n\007user_" +
      "id\030\001 \001(\r\"\'\n\013GetCartResp\022\030\n\004cart\030\001 \001(\0132\n." +
      "cart.Cart\"6\n\004Cart\022\017\n\007user_id\030\001 \001(\r\022\035\n\005it" +
      "ems\030\002 \003(\0132\016.cart.CartItem\"\017\n\rEmptyCartRe" +
      "sp2\251\001\n\013CartService\0220\n\007AddItem\022\020.cart.Add" +
      "ItemReq\032\021.cart.AddItemResp\"\000\0220\n\007GetCart\022" +
      "\020.cart.GetCartReq\032\021.cart.GetCartResp\"\000\0226" +
      "\n\tEmptyCart\022\022.cart.EmptyCartReq\032\023.cart.E" +
      "mptyCartResp\"\000B\032\n\013order.protoB\tCartProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cart_CartItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_CartItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_CartItem_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", });
    internal_static_cart_AddItemReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cart_AddItemReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_AddItemReq_descriptor,
        new java.lang.String[] { "UserId", "Item", });
    internal_static_cart_AddItemResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cart_AddItemResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_AddItemResp_descriptor,
        new java.lang.String[] { });
    internal_static_cart_EmptyCartReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cart_EmptyCartReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_EmptyCartReq_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_cart_GetCartReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cart_GetCartReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_GetCartReq_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_cart_GetCartResp_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cart_GetCartResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_GetCartResp_descriptor,
        new java.lang.String[] { "Cart", });
    internal_static_cart_Cart_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cart_Cart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_Cart_descriptor,
        new java.lang.String[] { "UserId", "Items", });
    internal_static_cart_EmptyCartResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cart_EmptyCartResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_EmptyCartResp_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
